name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - ".github/**"

  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      NUMEXPR_NUM_THREADS: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: System deps for scikit-learn
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libgomp1

      - name: Install project (+dev)
        run: |
          python -m pip install -U pip
          pip install -e .[dev]

      # API が読む学習済みモデルを用意
      - name: Prepare model for API smoke (adult fast)
        env:
          OMP_NUM_THREADS: "1"
          OPENBLAS_NUM_THREADS: "1"
          MKL_NUM_THREADS: "1"
          NUMEXPR_NUM_THREADS: "1"
        run: |
          make train-fast DS=adult
          ls -lh models/

      # ログを捨てずにファイルへ。失敗時に中身を吐く
      - name: Boot API in background
        run: |
          uvicorn api.app:app --host 127.0.0.x --port 8000 > api.log 2>&1 &
          for i in $(seq 1 100); do
            curl -sf http://127.0.0.x:8000/health >/dev/null && break
            sleep 0.2
          done
          curl -sf http://127.0.0.x:8000/health || { echo "==== api.log ===="; sed -n '1,200p' api.log; exit 1; }

      - name: Run tests (fast only)
        run: |
          pytest -q tests/test_api_smoke.py
          pytest -q tests/test_train.py -k test_train_builtin_fast
          MPLBACKEND=Agg python tests/test_perm.py --dataset=builtin --n-repeats=2 --max-samples=2000

      - name: Upload permutation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: perm-importance
          path: artifacts/

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          tags: mlops-sklearn-portfolio:test-ci
