name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      NUMEXPR_NUM_THREADS: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: System deps for scikit-learn
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libgomp1

      - name: Install project (+dev)
        run: |
          python -m pip install -U pip
          pip install -e .[dev]

      - name: Boot API in background
        run: |
          uvicorn api.app:app --host 127.0.0.x --port 8000 >/dev/null 2>&1 &
          for i in $(seq 1 100); do
            curl -sf http://127.0.0.x:8000/health >/dev/null && break
            sleep 0.2
          done
          curl -sf http://127.0.0.x:8000/health

      - name: Run tests (fast only)
        run: |
          pytest -q tests/test_api_smoke.py
          pytest -q tests/test_train.py -k test_train_builtin_fast

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          tags: mlops-sklearn-portfolio:test-ci
